### ISSUE TITLE
This issue, about payment fails because of decimal numbers, still exists using the nuget package

### ISSUE THREAD

**Issue by kevinleungwork** [AlejandroRuiz/PayPal.Forms#10]
![image](https://cloud.githubusercontent.com/assets/19150446/17105747/1286162e-52bb-11e6-9e44-4dd4783c9d1a.png)

The checkout fails for checkout payments with decimals (eg 12.99). If I use payments with no decimals, the payment will pass. 

- please note I am using the Android 5 on an emulator.

**Comment by fcogutierrez** [comment]
I am getting exactly the same problems than you @kevinleungwork

**Comment by kevinleungwork** [comment]
@fcogutierrez - Thanks for your message. Definitely our issues are related (probably similar). 

I have been trying various workarounds with this, but without success. The problem is passing the paypalitem array to the API for payment, where it will total to a decimal value and I suspect that this decimal total, is not to 2 decimal places. I tried converting all the paypalitem values to decimals , string then decimal ..etc but it seems there is nothing that can be done on our implementation (seems it's inside the nuget package).

@AlejandroRuiz - do you know how to fix this or point us to a solution? By the way, I tried to check the paypal.forms projects but there is an object reference error (to Xamarin.IOS) which prevents the solution from compiling.  I really like the work you did on this, because there are not many proper Xamarin payment solutions out there (I tried Judo but they are not good at all, and stripe is really inconvenient), but your solution is the best one I have found (well, up to payments with 2 decimal places).

**Comment by kevinleungwork** [comment]
Please refer to https://github.com/AlejandroRuiz/PayPal.Forms/issues/5 for the work in progress about this issue.
