### ISSUE TITLE
Latest Version against iOS10 complains about AOT compiling

### ISSUE THREAD

**Issue by voydz** [AlejandroRuiz/PayPal.Forms#16]
Hello there,

this library works just fine, if I deploy it on an iOS10 simulator. But if I try to deploy it on an actual device, the following error occurs while compiling:

> Could not AOT the assembly '/Users/felixrudat/Library/Caches/Xamarin/mtbs/builds/HDS.iOS/bddd3ff522751474c45d2b7db4be2e73/obj/iPhone/Debug/build-iphone7.1-10.0.2/mtouch-cache/Build/Xamarin.PayPal.iOS.dll'

Information about my development environment (it's a Windows machine running in Parallels on Mac)

> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01586
> 
> Installed Version: Enterprise
> 
> Architecture and Modeling Tools   00322-80000-00000-AA238
> Microsoft Architecture and Modeling Tools
> 
> UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
> 
> Visual Basic 2015   00322-80000-00000-AA238
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-80000-00000-AA238
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-80000-00000-AA238
> Microsoft Visual C++ 2015
> 
> Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA238
> Windows Phone SDK 8.0 - ENU
> 
> Application Insights Tools for Visual Studio Package   7.9.01018.2
> Application Insights Tools for Visual Studio
> 
> Command Bus, Event Stream and Async Manager   Merq
> Provides ICommandBus, IEventStream and IAsyncManager MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> File Nesting   2.5.63
> Automatically nest files based on file name and enables developers to nest and unnest any file manually
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> GorillaPlayerPackage Extension   1.0
> GorillaPlayerPackage Visual Studio Extension Detailed Info
> 
> Indent Guides   15
> Indent Guides
> 
> Adds visual guides at each indentation level.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JetBrains ReSharper Ultimate 2016.2.2    Build 106.0.20160913.91321
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> NuGet Package Manager   3.4.4
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> ReSharperAutoFormat   #114
> Automatically run ReSharper cleanup on save
> 
> SQL Server Data Tools   14.0.60519.0
> Microsoft SQL Server Data Tools
> 
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio
> 
> VSColorOutput   2.4
> Color output for build and debug windows - http://mike-ward.net/vscoloroutput
> 
> Xamarin   4.2.0.703 (3b7df6f)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android   7.0.1.3 (96c7ba6)
> Visual Studio extension to enable development for Xamarin.Android.
> 
> Xamarin.iOS   10.0.1.10 (ad1cd42)
> Visual Studio extension to enable development for Xamarin.iOS.

Any idea what is causing this issue? Thank you in advance.

greetings,
Felix

**Comment by AlejandroRuiz** [comment]
This is a Xamarin-Related issue, one version behind of the latest one was working fine but since Xamarin release the current version it introduced again this issue to test your app you can use next two escenarios:

1. Debug on Simulator.
2. Release on iOS Device.

I'll try to research about this issue to see if we can use a workaround

**Comment by voydz** [comment]
@AlejandroRuiz much appreciated, thanks

**Comment by acolangelo86** [comment]
@voydz go in properties on ios project, select iOS Build and in Linker Option set "Don't link". It will work fine
