### ISSUE TITLE
Is Adaptive Payment supported?

### ISSUE THREAD

**Issue by jamesatgithub** [AlejandroRuiz/PayPal.Forms#17]
Didn't see sample code for Adaptive Payment on readme, is this feature supported?
https://developer.paypal.com/docs/classic/products/adaptive-payments/

**Comment by AlejandroRuiz** [comment]
this is only supported via MPL(https://developer.paypal.com/docs/classic/mobile/gs_MPL/) which is not included in the standard iOS-Android PayPal Mobile SDK I need to research/test about it to see if it can belong to same lib or needs to create a new one

**Comment by jamesatgithub** [comment]
@AlejandroRuiz any update to the question?

**Comment by AlejandroRuiz** [comment]
as I said previously this is something not supported for Mobile SDK(which is the one that is used for this lib) so probably in the future I'll take time to create a lib for MPL

**Comment by jamesatgithub** [comment]
got it Thanks!
