### ISSUE TITLE
Android API <16 got Java.Lang.NoSuchMethodError: android.view.View.setBackground

### ISSUE THREAD

**Issue by cimoskill** [AlejandroRuiz/PayPal.Forms#18]
Hello,
I'm testing a new app using your PayPal.Forms on a tablet with Android 4.0.4.
Could be possible to implement the method setBackgroundResource instead which is available since version 1? I don't know if this is an issue or something, thank you anyway.
Simone

**Comment by AlejandroRuiz** [comment]
4.0.4 is not supported by PayPal SDK I recommend to target min 4.1(recommended) or 4.3(best)

**Comment by cimoskill** [comment]
thank you very much for your time n°1
