### ISSUE TITLE
Not work when change to Sandbox mode

### ISSUE THREAD

**Issue by leosoareslima** [AlejandroRuiz/PayPal.Forms#19]
Hi Alejandro,

This plugin work perfectly with NoNetwork configuration, but when I change to Sandbox mode, the sdk always return invalid password and username, calling the "CrossPayPalManager.Current.AuthorizeProfileSharing()" in Android.

In iOS, I never receive the authorizationCode, access in Result.ServerResponse.Response.Code.

Can you help me?
Thanks

**Comment by leosoareslima** [comment]
Sorry Alejandro, this problem was solved.
I had not created the sandbox test account before open this issue.
Consider resolved.

**Comment by AlejandroRuiz** [comment]
No problem let me close it
