### ISSUE TITLE
Droid Build Error

### ISSUE THREAD

**Issue by huepark** [AlejandroRuiz/PayPal.Forms#2]
[Environment]
- Xamarin Studio 5.10.3(Build51)
- Xamarin.Forms  2.2.0.31
- Xamarin.Android.Support.* 23.3.0
- PayPal.Forms 2.0.2

[Build Error Message]
Resources/Resource.designer.cs(220,127): error CS0117: `PaypalSample.Droid.Resource.Attribute' does not contain a definition for `mediaRouteSettingsDrawable'
	Resources/Resource.designer.cs(369,121): error CS0117: `PaypalSample.Droid.Resource.Color' does not contain a definition for `design_textinput_error_color'
	Resources/Resource.designer.cs(477,124): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `design_fab_content_size'
	Resources/Resource.designer.cs(487,138): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `design_navigation_padding_top_default'
	Resources/Resource.designer.cs(500,121): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `design_tab_min_width'
	Resources/Resource.designer.cs(501,126): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_height_major'
	Resources/Resource.designer.cs(502,126): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_height_minor'
	Resources/Resource.designer.cs(503,125): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_width_major'
	Resources/Resource.designer.cs(504,125): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_width_minor'
	Resources/Resource.designer.cs(510,141): error CS0117: `PaypalSample.Droid.Resource.Dimension' does not contain a definition for `mr_media_route_controller_art_max_height'
	Resources/Resource.designer.cs(597,114): error CS0117: `PaypalSample.Droid.Resource.Drawable' does not contain a definition for `ic_setting_dark'
	Resources/Resource.designer.cs(598,115): error CS0117: `PaypalSample.Droid.Resource.Drawable' does not contain a definition for `ic_setting_light'
	Resources/Resource.designer.cs(609,118): error CS0117: `PaypalSample.Droid.Resource.Drawable' does not contain a definition for `mr_ic_settings_dark'
	Resources/Resource.designer.cs(610,119): error CS0117: `PaypalSample.Droid.Resource.Drawable' does not contain a definition for `mr_ic_settings_light'
	Resources/Resource.designer.cs(630,90): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `art'
	Resources/Resource.designer.cs(634,94): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `buttons'
	Resources/Resource.designer.cs(649,108): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `default_control_frame'
	Resources/Resource.designer.cs(651,97): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `disconnect'
	Resources/Resource.designer.cs(676,112): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `media_route_control_frame'
	Resources/Resource.designer.cs(677,103): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `media_route_list'
	Resources/Resource.designer.cs(678,112): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `media_route_volume_layout'
	Resources/Resource.designer.cs(679,112): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `media_route_volume_slider'
	Resources/Resource.designer.cs(689,97): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `play_pause'
	Resources/Resource.designer.cs(694,97): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `route_name'
	Resources/Resource.designer.cs(710,95): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `settings'
	Resources/Resource.designer.cs(723,91): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `stop'
	Resources/Resource.designer.cs(725,95): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `subtitle'
	Resources/Resource.designer.cs(732,96): error CS0117: `PaypalSample.Droid.Resource.Id' does not contain a definition for `title_bar'
	Resources/Resource.designer.cs(780,124): error CS0117: `PaypalSample.Droid.Resource.Layout' does not contain a definition for `mr_media_route_chooser_dialog'
	Resources/Resource.designer.cs(781,138): error CS0117: `PaypalSample.Droid.Resource.Layout' does not contain a definition for `mr_media_route_controller_material_dialog_b'
	Resources/Resource.designer.cs(782,119): error CS0117: `PaypalSample.Droid.Resource.Layout' does not contain a definition for `mr_media_route_list_item'
	Resources/Resource.designer.cs(814,136): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_button_content_description'
	Resources/Resource.designer.cs(815,127): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_chooser_searching'
	Resources/Resource.designer.cs(816,123): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_chooser_title'
	Resources/Resource.designer.cs(817,131): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_disconnect'
	Resources/Resource.designer.cs(818,138): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_no_info_available'
	Resources/Resource.designer.cs(819,126): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_pause'
	Resources/Resource.designer.cs(820,125): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_play'
	Resources/Resource.designer.cs(821,141): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_settings_description'
	Resources/Resource.designer.cs(822,125): error CS0117: `PaypalSample.Droid.Resource.String' does not contain a definition for `mr_media_route_controller_stop'
	Resources/Resource.designer.cs(982,142): error CS0117: `PaypalSample.Droid.Resource.Style' does not contain a definition for `RtlOverlay_Widget_AppCompat_ActionButton_Overflow'
	Resources/Resource.designer.cs(1261,140): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `FloatingActionButton_android_background'
	Resources/Resource.designer.cs(1413,106): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme'
	Resources/Resource.designer.cs(1414,123): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarDivider'
	Resources/Resource.designer.cs(1415,130): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarItemBackground'
	Resources/Resource.designer.cs(1416,126): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarPopupTheme'
	Resources/Resource.designer.cs(1417,120): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarSize'
	Resources/Resource.designer.cs(1418,126): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarSplitStyle'
	Resources/Resource.designer.cs(1419,121): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarStyle'
	Resources/Resource.designer.cs(1420,127): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarTabBarStyle'
	Resources/Resource.designer.cs(1421,124): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarTabStyle'
	Resources/Resource.designer.cs(1422,128): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarTabTextStyle'
	Resources/Resource.designer.cs(1423,121): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarTheme'
	Resources/Resource.designer.cs(1424,127): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionBarWidgetTheme'
	Resources/Resource.designer.cs(1425,124): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionButtonStyle'
	Resources/Resource.designer.cs(1426,126): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionDropDownStyle'
	Resources/Resource.designer.cs(1427,131): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionMenuTextAppearance'
	Resources/Resource.designer.cs(1428,126): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionMenuTextColor'
	Resources/Resource.designer.cs(1429,127): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeBackground'
	Resources/Resource.designer.cs(1430,133): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeCloseButtonStyle'
	Resources/Resource.designer.cs(1431,130): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeCloseDrawable'
	Resources/Resource.designer.cs(1432,129): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeCopyDrawable'
	Resources/Resource.designer.cs(1433,128): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeCutDrawable'
	Resources/Resource.designer.cs(1434,129): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeFindDrawable'
	Resources/Resource.designer.cs(1435,130): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModePasteDrawable'
	Resources/Resource.designer.cs(1436,133): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModePopupWindowStyle'
	Resources/Resource.designer.cs(1437,134): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeSelectAllDrawable'
	Resources/Resource.designer.cs(1438,130): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeShareDrawable'
	Resources/Resource.designer.cs(1439,132): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeSplitBackground'
	Resources/Resource.designer.cs(1440,122): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeStyle'
	Resources/Resource.designer.cs(1441,134): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionModeWebSearchDrawable'
	Resources/Resource.designer.cs(1442,132): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionOverflowButtonStyle'
	Resources/Resource.designer.cs(1443,130): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_actionOverflowMenuStyle'
	Resources/Resource.designer.cs(1444,131): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_activityChooserViewStyle'
	Resources/Resource.designer.cs(1445,134): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_alertDialogButtonGroupStyle'
	Resources/Resource.designer.cs(1446,131): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_alertDialogCenterButtons'
	Resources/Resource.designer.cs(1447,123): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_alertDialogStyle'
	Resources/Resource.designer.cs(1448,123): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_alertDialogTheme'
	Resources/Resource.designer.cs(1449,135): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_android_windowAnimationStyle'
	Resources/Resource.designer.cs(1450,131): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_android_windowIsFloating'
	Resources/Resource.designer.cs(1451,132): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_autoCompleteTextViewStyle'
	Resources/Resource.designer.cs(1452,128): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_borderlessButtonStyle'
	Resources/Resource.designer.cs(1453,127): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_buttonBarButtonStyle'
	Resources/Resource.designer.cs(1454,135): error CS0117: `PaypalSample.Droid.Resource.Styleable' does not contain a definition for `Theme_buttonBarNegativeButtonStyle'

Would you please provide some solution for this?

**Comment by AlejandroRuiz** [comment]
@huepark could you provide me more info about the issue ie. Device, Device Os Ver, App Target SDK, Minimum & Target Framework, also I released a new version that it is builded for forms 2.2.0.32 and Support Libraries 23.3.3.0 https://www.nuget.org/packages/PayPal.Forms/2.0.3 please let me know if the new release fix your issue
