### ISSUE TITLE
Nuget error

### ISSUE THREAD

**Issue by xerotolerant** [AlejandroRuiz/PayPal.Forms#21]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Package 'PayPal.Forms 2.15.7' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.			0	

I am getting this error when attempting to install it off of nuget in visual studio.
EDIT: this occurs only with version 2.15.7; version 2.15.5 seems to be working

**Comment by CMorooney** [comment]
Also seeing this issue, fwiw

**Comment by AlejandroRuiz** [comment]
Sorry I was a little bit busy but Ill upload a fix for this over the weekend

**Comment by AlejandroRuiz** [comment]
@xerotolerant @CMorooney I just release version 2.6.0 try installing it if you continue having issue with that try adding next feed source in your nuget config https://www.nuget.org/api/v2
