### ISSUE TITLE
PayPal.Forms 2.15.5 Issue while install from nuget

### ISSUE THREAD

**Issue by coolricky728** [AlejandroRuiz/PayPal.Forms#22]
'PayPal.Forms 2.15.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AlejandroRuiz** [comment]
Duplicate #21

**Comment by AlejandroRuiz** [comment]
@coolricky728 to make this work change your PCL profile to 78
