### ISSUE TITLE
Integration without forms

### ISSUE THREAD

**Issue by AeonDave** [AlejandroRuiz/PayPal.Forms#24]
Hello,
i have a project with ios/android native xamarin (c#) application and i would know if there is any possibility to use this library without xamarin forms.

Thank you!

**Comment by AlejandroRuiz** [comment]
I'll separate bindings projects into a separate nuget packages probably it will be available over this weekend

**Comment by AlejandroRuiz** [comment]
Hey @AeonDave now we have separate nuget for 
Xamarin.PayPal.Android.CardIO
Xamarin.PayPal.Android
Xamarin.PayPal.iOS

you can see native implementation examples from here:
Android: https://github.com/AlejandroRuiz/PayPal.Forms/tree/master/MobileApps/PayPal.Forms/PayPalAndroidTest

iOS: https://github.com/AlejandroRuiz/PayPal.Forms/tree/master/MobileApps/PayPal.Forms/PayPalAndroidTest/PayPayiOSTest
