### ISSUE TITLE
How do I pay with id seller?

### ISSUE THREAD

**Issue by SrCristian** [AlejandroRuiz/PayPal.Forms#27]
Now, I can work in test mode, but I need work in pay mode.
Where I write the id of the seller? Do I need to do something in the paypal acount?
Thanks you.

**Comment by AlejandroRuiz** [comment]
you can check the config here https://github.com/AlejandroRuiz/PayPal.Forms#setup

basically you need to set the id from your paypal portal here:

`new PayPalConfiguration(PayPalEnvironment.NoNetwork,"Your PayPal ID from https://developer.paypal.com/developer/applications/")`

**Comment by SrCristian** [comment]
Thanks you for you help.
Now I have another question. How can I disable the camera functions and pay with credit number?

**Comment by AlejandroRuiz** [comment]
To enable direct credit cards, you will enable this feature through PayPal account eligibility and camera feature is enabled by default on Mobile SDK

Ref => https://developer.paypal.com/developer/accountStatus

**Comment by SrCristian** [comment]
Thanks you for you help.
