### ISSUE TITLE
Paypalnot installed and not getting any return value  in Xamarin forms

### ISSUE THREAD

**Issue by sureshtest** [AlejandroRuiz/PayPal.Forms#28]
Hi AlejandroRuiz greatly done the Plugin for Paypal but. iam unable to install in xamarin forms. you suggest in some forums to install the 2.15.5 & 2.15.4 version 2.15.5 installed but i am trying those versions but not installed. and one more i am configured the Paypal Cleint id configure in xamarin android.could you please suggest the solution for this

**Comment by DarnelleF** [comment]
@sureshtest could u be more specific with the error you are getting? i would like to ask what pcl profile you have?

**Comment by sureshtest** [comment]
@DarnelleF  i am unable to install the "PayPal.Forms" versions from nuget package in visualstudio 2015. and one more question. i am not getting any return value(Success Message) from "PayPal" in xamarin forms.please help me to resolve this issues eating time from past 10 days

**Comment by DarnelleF** [comment]
@sureshtest i cant help u until u give me specific error messages while installing, and if you cant install paypal.forms u wont bea ble their api. if u want help specific errors would be appreciated

**Comment by AlejandroRuiz** [comment]
@sureshtest please provide more info about your installing issue also a note this lib works for PCL profile 78

**Comment by sureshtest** [comment]
when i am clicking paypal button then return any payment id in xamarin forms there is no error
