### ISSUE TITLE
Email of the paying user

### ISSUE THREAD

**Issue by acolangelo86** [AlejandroRuiz/PayPal.Forms#29]
Hi,

how can I retrieve the email of the account paypal that paid through this implementation?

regards
James

**Comment by AlejandroRuiz** [comment]
Hey that's something that Mobile SDK is not providing, take a look to this stackoverflow answer http://stackoverflow.com/questions/23201544/how-to-get-buyers-info-in-paypal-mobile-sdk this is something that you'll need to do in server side.

PayPal Ref:
https://developer.paypal.com/docs/api/payments/#payment_get

**Comment by acolangelo86** [comment]
Please can you tell me how can I retrieve the email of the buyer on Paypal server side?
I searched in server side PayPal sdk documentation but I have not found any code to retrieve the email of the buyer.
Please if you find a solutions please write some links.
Thanks.
James.

**Comment by AlejandroRuiz** [comment]
@acolangelo86 please check the above links, basically is to call this endpoint /v1/payments/payment/payment_id you can see the sample curl call with that you will be able to do that call in the language that you want
