### ISSUE TITLE
App crash on close

### ISSUE THREAD

**Issue by xerotolerant** [AlejandroRuiz/PayPal.Forms#32]
The app crashes with the error:
This occurs on android 7.0 on a Samsung galaxy s6. 
`System.NullReferenceException: ObjectException: Object reference not set to an instance of an object.`

This occurs when `OnDestroy()` is called.

When I exit my application and 
`PayPalManangerImplementation.Manager.Destroy();` is called.

I'm working around the error with a try catch block but it doesn't seem right to be catching an error an exception and doing nothing.
What can I do to avoid this?

**Comment by oaestella** [comment]
Experiencing this issue as well, with my Zenfone 3, Android 7.0, throws a NullReferenceException.

I have no other lines of code in my `OnDestroy()` event in my MainActivity.
Any workaround to fix this?

**Comment by AlejandroRuiz** [comment]
Currently im researching about the issue seems that is an Android 7.0 issue

**Comment by AlejandroRuiz** [comment]
This is currently fixed on version 2.17.1

**Comment by J-Pabon** [comment]
I am currently experiencing this with version 2.18.0 on a Pixel with Android 8.1.0

**Comment by jagunosra** [comment]
i have experienced this on android 8.10 also
