### ISSUE TITLE
Checks before CrossPayPalManager.Current.Buy

### ISSUE THREAD

**Issue by FCristallo** [AlejandroRuiz/PayPal.Forms#35]
Before the purchase phase and the istant sale (PaymentIntent = sale) I need to check:

-  if the payer's account is verified 
- country Code of buyer

In the web site I use the offical paypal sdk and I use the following code:
```

 var paymentDetails = Payment.Get( apiContext, paymentID );
if ( paymentDetails.payer.status != PAYER_VERIFIED ) {
    throw new Exception( $"-- PaymentGatewayService - ExecutePayment - Payer not verified" );
}
if ( paymentDetails.payer.payer_info.country_code != PAYER_COUNTRY_IT ) {
    throw new Exception( $"-- PaymentGatewayService - ExecutePayment - Invalid Payer country code" );
}
var paymentExecution = new PaymentExecution() { payer_id = payerID };
result = Payment.Execute( apiContext, paymentID, paymentExecution );
```
In the related App it's possible to do the same flow with your library?

**Comment by AlejandroRuiz** [comment]
The mobile sdk only provides a very simple data you can take a look to the next properties that the only data that Mobile SDK returns

https://github.com/AlejandroRuiz/PayPal.Forms/blob/master/MobileApps/PayPal.Forms/PayPal.Forms/PayPal.Forms.Abstractions/PaymentResult.cs


If you need more data you will need to do that on your backend side please see this http://stackoverflow.com/questions/23201544/how-to-get-buyers-info-in-paypal-mobile-sdk

PayPal Ref:
https://developer.paypal.com/docs/api/payments/#payment_get
