### ISSUE TITLE
Problem with xcode 9/Xamarin.IOS 11.0.0.0

### ISSUE THREAD

**Issue by DaniGiana** [AlejandroRuiz/PayPal.Forms#37]
I updated Xcode9 e Xamarin.IOS 11.0.0.0 and the components crash on the "await CrossPayPalManager"....how can i resolve this problem? Thanks

**Comment by AlejandroRuiz** [comment]
I just tested on my device and is working fine both simulator / iPhone 7 plus please provice me more insights about your crash logs, screenshoots, device, OS version, etc

**Comment by AlejandroRuiz** [comment]
Closed due inactivity
