### ISSUE TITLE
how to re-initialize CrossPayPalManager?

### ISSUE THREAD

**Issue by RichardK68** [AlejandroRuiz/PayPal.Forms#39]
Hi,

We have an app in the development phase that allows users to select from a list of businesses and purchase stuff from that business. The paypal id is passed over to the app from the business for payment and initialized with CrossPayPalManager.Init(). However, when changing business and attempting to re-initialize with the new paypal id and environment it appears to be ignoring the new information (our test businesses use a combination of nonetwork and sandbox to test this functionality). e.g. initialize for first time with paypalid xxx and nonetwork,make payment (mock data),choose second business (paypalid xxx and sandbox),make payment (it still says mock data when it should say sandbox) . We are currently using the same paypalid for testing the different businesses.

We would like to be able to re-initialize paypal for the currently selected business from within the app without having the user kill the app and re-open to choose another business.

How do we go about doing this? If it can't currently do it I'd like to request new functionality for that.

Thanks!

**Comment by AlejandroRuiz** [comment]
Right now this is not supported I'll flag this as an enhancement for next release

**Comment by RichardK68** [comment]
Thanks for that! When is this change likely to be released? We imagine it would be a very small change to allow the current merchant to be changed. We would like it as soon as we can as this is the only thing stopping us from releasing our app. We don't like the idea of implementing another payment system, especially a client/server, that is way too much messing about. This plugin has been a dream to integrate, there have been no problems apart from this.

**Comment by AlejandroRuiz** [comment]
You're a lucky man, I'm just testing 2.17.1 which is up now, you'll be able to update the package right now, and it contains this new feature

**Comment by AlejandroRuiz** [comment]
Just use CrossPayPalManager.Current.SetConfig(); please let me know if you have any feedback on it

**Comment by RichardK68** [comment]
You're a legend. Downloaded and installed, had some minor issues to tidy up.
Changed the CrossPayPalManager.Init to CrossPayPalManager.Current.SetConfig
but it tells me I have to call CrossPayPalManager.Init() first. 

So do we use Init() for the first time we initialize for a merchant and SetConfig() for subsequent merchants?

Richard

**Comment by AlejandroRuiz** [comment]
thats right this first one is to set the default and SetConfig() is if you need to update the info if you didn't know the info at the beginning you can use any dummy data for Init()

**Comment by AlejandroRuiz** [comment]
the Context of the app you can use something like this

Forms.CrossPayPalManager.Init (
				new PayPalConfiguration (PayPalEnvironment.NoNetwork, "YOUR ID STRING")
                {
					AcceptCreditCards = true,
					MerchantName = "Test Store",
					MerchantPrivacyPolicyUri = "https://www.example.com/privacy",
					MerchantUserAgreementUri = "https://www.example.com/legal"
				},
                this
			);

**Comment by RichardK68** [comment]
That worked! Thank you for all your help!

We are using the same paypalid for testing but changing between mock data and sandbox for the test businesses we were using, this never changed but with this latest update it works well! Thanks!

One last thing ... is it possible to turn off the camera/card scanning feature?

**Comment by RichardK68** [comment]
The Android side of things with the SetConfig() is working fine but the iOS doesn't seem to know the new method. I installed the latest version with Install-Package PayPal.Forms -Version 2.17.1 which is the command I used under Android but the method doesn't show up in intellisense.

Was this implemented in both iOS and Android? Maybe my install command didn't work properly under iOS.

**Comment by AlejandroRuiz** [comment]
Yes I just tested on both and are working fine try removing package and re-adding it

**Comment by RichardK68** [comment]
All good now, thanks heaps. I'd changed from Android to iOS within VS and installed the package, but VS hadn't registered the changeover. So I did it all again. iOS is registering the change of business from mock data to sandbox and back again, all good.

On Android when we use sandbox with credit card 4242 4242 4242 4242 it gives us a messagebox saying invalid payment method or something similar.

When we use sandbox from iOS after pressing Charge card it pops up the processing message and spinning wheel and animates for about 20 seconds then just drops to the iPad desktop.

Thought you might like to know about that,.

**Comment by RichardK68** [comment]
Cool, I'll check that out soon and get back to you with the console output, I've got bogged down in other stuff unfortunately :(

**Comment by RichardK68** [comment]
We've found that our notifications have stopped working, the app fails to register with 

"Java.Lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in ...

And this is because the project now requires Xamarin.Android.Support.v4.25.4.02 but we were previously using Xamarin.Android.Support.v4.23.3.0. I've tried removing the v4.25 folder and replacing with the original but then the project won't compile.

The only thing we added today is the upgrade for the PayPal? Do you know of an easy solution for this?

Thanks!

**Comment by AlejandroRuiz** [comment]
You'll need to update your code to support that version since Xamarin.Forms 2.5 supports v4.25

**Comment by RichardK68** [comment]
Sorry about the delay in replying. I had a TIA on the 6th of December and have taken the last month off work.

I've updated both Android and iOS projects with this

Install-Package Xamarin.Firebase.Messaging -Version 60.1142.0

I still get
"Java.Lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in... 

Thanks!

Richard

**Comment by RichardK68** [comment]
Sorry, I meant

Install-Package Xamarin.Forms -Version 2.5.0.122203

(damn clipboard)

It seems that with the update to the PayPal version with the fix/enhancement for re-initializing the PayPal business, and the move to version 2.5 of Forms, there is now a clash with the push notifications plugin we are using. I know you aren't responsible for that plugin but everything was working until the PayPal upgrade. Can you offer any help on what I should do to resolve this? These package conflicts are a pain in the @## !

Richard
