### ISSUE TITLE
Can't install plugin Xamarin Forms

### ISSUE THREAD

**Issue by luidgisarto** [AlejandroRuiz/PayPal.Forms#40]
![image](https://user-images.githubusercontent.com/16051308/33582557-ed28de48-d93c-11e7-8117-a57d26c05eef.png)

I have tried installing the paypal plugin for xamarin forms with prism, and there is always the same error when installing the nuget package, I already tried to reduce the version and install the first ones, and the error still persists, I use the .NET Framework 4.5

**Comment by AlejandroRuiz** [comment]
I just uploaded version 2.17.1 which is compatible with profile259 and .netstandards1.x try to download it
