### ISSUE TITLE
Exception when using cards - IOS

### ISSUE THREAD

**Issue by bojanculafic** [AlejandroRuiz/PayPal.Forms#41]
Hi,

I am using your latest library and I am getting an exception when I try to pay with a Credit Card.
 This is happening only in Xamarin.IOS.

**PayPal Binding Lib for Xamarin.iOS**
2.17.0 (when I start up the PayPal view, it shows **Sandbox 2.16.1** Is this correct? )

**Credit Card (test card)**
4111 1111 1111 1111
11/18                    123

**Simulator**: iPhone X iOS 11.2
(it's happening on real devices also)

When I try to pay something I am getting the following exception:

**Unhandled Exception:**

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
Native stack trace:
	0   CoreFoundation                      0x000000011504112b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000115dd1f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115059ebd -[__NSArray0 objectAtIndex:] + 93
	3   mcs.mobile.iOS                      0x0000000106695995 +[PPAPIResponseDictionary filterResponse:type:] + 1365
	4   mcs.mobile.iOS                      0x0000000106694fd4 -[PPAPIResponseDictionary initWithType:response:environemnt:] + 223
	5   mcs.mobile.iOS                      0x0000000106695257 +[PPAPIResponseDictionary responseWithType:response:environment:] + 92
	6   mcs.mobile.iOS                      0x00000001066637f0 __77-[PPServiceManager processCreditCardPayment:completion:withPreviousResponse:]_block_invoke.321 + 234
	7   mcs.mobile.iOS                      0x000000010666328a __110-[PPServiceManager handleRequestResponseWithRetryBlock:withFailBlock:withCreateRequestBlock:withSuccessBlock:]_block_invoke.296 + 327
	8   mcs.mobile.iOS                      0x00000001066563a3 -[PPServiceRequest urlConnection:didSucceedWithData:] + 278
	9   mcs.mobile.iOS                      0x00000001066a0d51 __28-[PPSimpleURLConnection win]_block_invoke + 427
	10  libdispatch.dylib                   0x0000000116ee3177 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x0000000116ee41ba _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000116eee3a4 _dispatch_main_queue_callback_4CF + 1260
	13  CoreFoundation                      0x0000000115003e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x0000000114fc8462 __CFRunLoopRun + 2402
	15  CoreFoundation                      0x0000000114fc7889 CFRunLoopRunSpecific + 409
	16  GraphicsServices                    0x00000001179299c6 GSEventRunModal + 62
	17  UIKit                               0x00000001077f25d6 UIApplicationMain + 159
	18  ???                                 0x00000001347144a8 0x0 + 5174805672
	19  ???                                 0x00000001347140e3 0x0 + 5174804707
 occurred 

Could you please check this? 

I would be glad to provide you more information if needed. I also found a same/similar issue here https://github.com/paypal/PayPal-iOS-SDK/issues/562 .

Thank you,
Bojan

**Comment by AlejandroRuiz** [comment]
Im just uploading to version 2.18.0 this will be available in a couple of hours

**Comment by AlejandroRuiz** [comment]
Version 2.18.1 is up and is working as expected

**Comment by bojanculafic** [comment]
I've tried the latest version. It works as expected.

Thank you!
