### ISSUE TITLE
Xamarin.Forms

### ISSUE THREAD

**Issue by costvin15** [AlejandroRuiz/PayPal.Forms#43]
The application return this message after call CrossPaypalManager.Current.Buy: 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

![image](https://user-images.githubusercontent.com/35884309/35478956-c9b0e0a4-03d1-11e8-8f82-3cadf279f103.png)

**Comment by AlejandroRuiz** [comment]
Please be sure that you have PayPal package added into your iOS & Android projects
