### ISSUE TITLE
PayPal.Forms for Xamarin.Forms including UWP

### ISSUE THREAD

**Issue by JORGEGO** [AlejandroRuiz/PayPal.Forms#44]
HI,
are any possibility to use PayPal.Forms for xamarin.forms target UWP? I am devolping a solution and I need to support Andorid / IOS and UWP

Thanks

**Comment by AlejandroRuiz** [comment]
Right now PayPal Mobile SDK doesn't support UWP probably you'll need to create your own impl. for UWP
