### ISSUE TITLE
Payment with credit card fails the second time - Android/iOS 

### ISSUE THREAD

**Issue by bojanculafic** [AlejandroRuiz/PayPal.Forms#45]
When credit card is used for payment, the first time everything is ok, but the second time error dialog is shown with the following message:

--------------------------------------
Payment Failed
--------------------------------------
System error. Please try again later.
--------------------------------------

Logs:
02-09 23:07:41.857 W/paypal.sdk(22981): fd SN:17 PayPal Debug-ID: 9b5f2204d010 [sandbox, 2.15.3;release]
02-09 23:07:41.857 E/paypal.sdk(22981): request failure with http statusCode:500,exception:
02-09 23:07:41.877 E/paypal.sdk(22981): request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"9b5f2204d010"}
02-09 23:07:41.877 E/paypal.sdk(22981): INTERNAL_SERVICE_ERROR

Steps to reproduce the problem:
1.) Pay with a credit card
2.) Trigger payment with saved card information from the previous step

Credit card used:
4111 1111 1111 1111
11/18                    123

If the information about the card is cleared and added again, it works.

Both, Android and iOS, platforms are affected.

Is there a way not to remember the card information? Some other workaround?

If you need more information, please ask.

Thank you,
Bojan

**Comment by AlejandroRuiz** [comment]
Yes just set the StoreUserData in your PayPalConfig settings to false https://github.com/AlejandroRuiz/PayPal.Forms/blob/6c191926584e813eb000d3e1f46c888a44c0bef3/MobileApps/PayPal.Forms/PayPal.Forms/PayPal.Forms.Abstractions/PayPalConfiguration.cs#L23
