### ISSUE TITLE
Just a question, Is it possible to add a donate link view?

### ISSUE THREAD

**Issue by edgar-mtz-e** [AlejandroRuiz/PayPal.Forms#46]
I searched for donate function but didn´t find any, Is it possible?

**Comment by AlejandroRuiz** [comment]
This feature is not part of mobile SDK you will need to implement in a separate page in order to make it work. You can see that is not supported on the official PayPal mobile SDK GitHub repo https://github.com/paypal/PayPal-iOS-SDK/issues/249
