### ISSUE TITLE
System.NullReferenceException Error on Buy method

### ISSUE THREAD

**Issue by renatotozzi** [AlejandroRuiz/PayPal.Forms#48]
Hi everybody

I'm trying to use this package and I'm facing an issue. When I call the "CrossPayPalManager.Current.Buy" method, I get this System.NullReferenceException error.

I'm using:
- Windows 10
- Visual Studio 2017
- Xamarin Forms 2.5.0.280555
- Android 7.1 Nougat API 25 emulator.

See below all configuration of my project:

![oncreate](https://user-images.githubusercontent.com/6411176/38034561-8ed00e10-3270-11e8-9934-160fd85ae2fa.png)

![overrides](https://user-images.githubusercontent.com/6411176/38034579-9908cb1a-3270-11e8-92af-2a14258d63e0.png)

At this point below...

![mainpage](https://user-images.githubusercontent.com/6411176/38034610-a84ef13a-3270-11e8-8d4d-8ead1764ada4.png)

I get the error:

![error](https://user-images.githubusercontent.com/6411176/38034647-bc82e79c-3270-11e8-8c04-8f48f0bd7f25.png)

If anyone can help me, I thank you!

Best regards

**Comment by renatotozzi** [comment]
Update: I downgrade PayPal.Forms to version 2.16.2 and it works. So, the problem is in latest version 2.18.1

**Comment by AlejandroRuiz** [comment]
Instead of use “this.ApplicationContext” try using “this” seems that the doc need an update but hope that helps

**Comment by renatotozzi** [comment]
OMG it works!!!!

Why haven't I thought about to do by this way before? =(

In fact you need to update the doc, just that.

Very very thanks, man!

--
Att,
Renato Tozzi
________________________________
De: Alejandro Ruiz Varela <notifications@github.com>
Enviado: quinta-feira, 29 de março de 2018 12:24
Para: AlejandroRuiz/PayPal.Forms
Cc: renatotozzi; Author
Assunto: Re: [AlejandroRuiz/PayPal.Forms] System.NullReferenceException Error on Buy method (#48)


Instead of use “this.ApplicationContext” try using “this” seems that the doc need an update but hope that helps
