### ISSUE TITLE
PayPal isn't making any transaction

### ISSUE THREAD

**Issue by Qasid12** [AlejandroRuiz/PayPal.Forms#50]
I created Xamarin forms app using your provided code, its working perfect but I couldn't make any transaction. I get response from server that transaction is successful but when I check on my paypal account no any transaction happens.

**Comment by AlejandroRuiz** [comment]
You need to provide more insighrs
Plugin version
Device/simulator Os & version
Enviroment
Crash or error logs
Demo code

**Comment by AlejandroRuiz** [comment]
Please double check that you have correctly setup the enviroment and also api key on that code seems that you’re using no network and a no valid api key

**Comment by Qasid12** [comment]
You are right Sir. 
I need to setup paypal rest api. 
Thanks for your help

**Comment by Qasid12** [comment]
Hi AlejandroRuiz
sorry to bother you again. Ive created paypal rest api and got my live account creditionals but still I couldnt make a transaction. It does connects to paypal. Ive spoken to paypal they said this issue is from my side.
what changes Ive made I will send you now.

 var config = new PayPalConfiguration(PayPalEnvironment.Production, "client id")

**Comment by AlejandroRuiz** [comment]
Just go to your Rest Api Apps and select the enviroment that you want then copy your ClientId string and pass it as parameter in the PayPalConfiguration class that all

**Comment by Qasid12** [comment]
thanks alot sir I am doing exactly same. But it won't let my transaction going through. 
I text you my error. "There was a problem setting up this payment. Please visit the paypal website to check your  account"
I am using live account creditionals of rest api.
