### ISSUE TITLE
example on how to scan a card, store it and pay with it on demand

### ISSUE THREAD

**Issue by egarim** [AlejandroRuiz/PayPal.Forms#51]
Hi
first, let me tell you that you have created an amazing plugin. I want to create a flow in my app but I don't know if its possible. here is a description

1) the user can scan 1 or multiple cards and store the info in the app.
2) the user should set one of the cards as default card
3)any future payment will be done with the card that is select as default without the user intervention 

the flow is basically the same as the flow on uber.

**Comment by Qasid12** [comment]
Hi egarim
I couldn't make transaction using this plugin. Are you be able to make?

**Comment by egarim** [comment]
No I was not able

**Comment by AlejandroRuiz** [comment]
1 You can scan cards many cards as you need using the standalone card scanner and store them wherever you want

2 you can select wheter card will be used for your transactions

3 future payments are available please review readme file for docs

https://github.com/AlejandroRuiz/PayPal.Forms/blob/master/README.md

**Comment by egarim** [comment]
Thanks Alejandro, thanks for your answer, I got another questions.
1) So I have the cards already stored, how can I pass them to the buy method if it does not have any overload that uses the card object.

2) according to this link (https://developer.paypal.com/docs/integration/mobile/make-future-payment/) future payments are not supported anymore, so is the future payment method a legacy method or are you handling future payments in a different way?
