### ISSUE TITLE
Please support UWP!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [AlejandroRuiz/PayPal.Forms#54]
Your plugin is awesome, please support UWP!
Thank you!

**Comment by AlejandroRuiz** [comment]
UWP is not supported by PayPal Mobile SDK

**Comment by amirvenus** [comment]
Will UWP be supported anytime soon?

**Comment by AlejandroRuiz** [comment]
@amirvenus as I mentioned previously PayPal Mobile SDK doesn't support UWP so isn't possible to add support for UWP

**Comment by nguyenthanhliemfc** [comment]
Mobile is dead. But UWP still alive on Windos 10 devices. Will PayPal support UWP for Windos!
