### ISSUE TITLE
installation problems - android

### ISSUE THREAD

**Issue by anneiman** [AlejandroRuiz/PayPal.Forms#59]
Hello, 
I installed packages PayPal.Forms and Xamarin.PayPal.Android, but still get the error"
"The name 'CrossPayPalManager' does not exist in the current context	..."

Any PayPal* names are not visible in object browser

I use Xamarin in Visual Studio 2017 and tried  to install various versions of the packages above.
Please, let me know what's wrong.
Thanks

**Comment by anneiman** [comment]
Probably, it is the problem between syncfusion and paypal.forms


I removed the references and and try to install manually and get

Install-Package : An error occurred while retrieving package metadata for 'PayPal.Forms.2.18.3' from source 'syncfusion'.
The V2 feed at 'http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin/Packages(Id='PayPal.Forms',Version='2.18.3')' returned an unexpected status code '500 Internal Server Error'.
At line:1 char:1

Install-Package PayPal.Forms -Version 2.18.3
~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], Exception
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
Now , when I removed syncfusion from the packages sources, it passed OK

**Comment by AlejandroRuiz** [comment]
Please be sure that you're using the official nuget feed url
