### ISSUE TITLE
Paypal account credentials authentication

### ISSUE THREAD

**Issue by manasa1** [AlejandroRuiz/PayPal.Forms#68]
On click of **Pay with PayPal** button,if wrong credentials entered in  Email & Password fields it is navigating to "confirm" page.

How to check whether the credentaials entered is right or wrong?How can i authenticate.

**Comment by AlejandroRuiz** [comment]
Is because you're using PayPalEnvironment.NoNetwork enviroment please make sure that you use eiter Sandbox or Production to test with real/test accounts
