### ISSUE TITLE
How to add multiple item dynamically using code behind?

### ISSUE THREAD

**Issue by masroorejaz** [AlejandroRuiz/PayPal.Forms#69]
Hello,

I want to add multiple item using code behind. But when I used the following code it only add last line of PayPal Items to PayPal list:

int CartCount=_CarttList.Length;

 PayPalItem[] PayPalItems = new PayPalItem[] { };

for(int i=0;i<CartCount;i++)
{
    PayPalItems = new PayPalItem[] { new PayPalItem(_CarttList[i].ProductName, _CarttList[i].Qty, _CarttList[i].Price, _CarttList[i].Currency, _CarttList[i].SKU };
}

var result = await CrossPayPalManager.Current.Buy(new PayPalItem[] { PayPalItemTest },Shipping, Tax);

Any help would be appreciated.

Thank you.

**Comment by AlejandroRuiz** [comment]
you have wrong code please use as next

int CartCount=_CarttList.Length;

List<PayPalItem> PayPalItems = new List<PayPalItem>();

for(int i=0;i<CartCount;i++)
{
PayPalItems.Add(new PayPalItem(_CarttList[i].ProductName, _CarttList[i].Qty, _CarttList[i].Price, _CarttList[i].Currency, _CarttList[i].SKU);
}

var result = await CrossPayPalManager.Current.Buy(PayPalItems.ToArray(), Shipping, Tax);
