### ISSUE TITLE
[iOS] Wrong behavior when setting the ShippingAddress on .Buy() method

### ISSUE THREAD

**Issue by fcogutierrez** [AlejandroRuiz/PayPal.Forms#7]
When I call to the buy method with any shipping address:

```
var shippingAddress = new ShippingAddress("Test name", "Test address", string.Empty, "Málaga", "Málaga", "29006", "Spain");

var paymentResult = await CrossPayPalManager.Current.Buy(paypalItems, new Decimal(0), new Decimal(0), shippingAddress);

```
In the payment result I get the following message: _"This particular payment will always be processable. If, for example, the amount was negative or the shortDescription was empty, this payment wouldn't be processable, and you'd want to handle that here."_ and _Cancelled_ as status.

...and **the Paypal popup never apperars**.

PD: in Android works fine.

**Comment by AlejandroRuiz** [comment]
@fcogutierrez  I found the root issue you're setting the country code as a "Spain" but regarding paypal docs you need to use "ES" check the follow docs to see all country codes supported by paypal https://developer.paypal.com/docs/classic/adaptive-accounts/integration-guide/ACCountryCodes/

**Comment by fcogutierrez** [comment]
Thanks @AlejandroRuiz.
