### ISSUE TITLE
Lokio/Async 

### ISSUE THREAD

**Issue by jagunosra** [AlejandroRuiz/PayPal.Forms#72]
Severity	Code	Description	Project	File	Line	Suppression State
Error		java.lang.IllegalArgumentException: already added :  Lokio/AsyncTimeout;	HiDokAPP.Android			

I received an error on this issue after I installed and compiled the project. May i know how to fix this?

**Comment by AlejandroRuiz** [comment]
Please detail a bit your case is this happening in debug/release with or without proguard enabled?

**Comment by jagunosra** [comment]
this issue has been fixed.
