### ISSUE TITLE
App Crashes when close using back button on Android

### ISSUE THREAD

**Issue by whitewabbit** [AlejandroRuiz/PayPal.Forms#73]
When I open my app and close it using the back button in android. It will break at PayPalManagerImplementation.Manager.Destroy(); and crashes.
I used the Latest "stable" version (Version 2.18.3)

**Comment by AlejandroRuiz** [comment]
Working on a fix new version will be released today

**Comment by AlejandroRuiz** [comment]
Fixed on version 2.18.5
