### ISSUE TITLE
Adding discount

### ISSUE THREAD

**Issue by amirvenus** [AlejandroRuiz/PayPal.Forms#74]
Hi,

I was just wondering if that would be possible to add a PayPalItem whose price is less than zero to give discount to customers.

At the moment when I do that, it just cancels the payment without even prompting for PayPal/Card Details.

**Comment by AlejandroRuiz** [comment]
No is supposed that you need to charge a valid price not a 0 or less values in that case you need to handle that logic on your app side code

**Comment by amirvenus** [comment]
Thanks!

I figured that out but I asked that question because a lot of times on PayPal receipts generated on other website I have seen the discount value (a negative number).

But thanks for your response and keep up the good work!
