### ISSUE TITLE
Get address to deliver in the PaymentResult

### ISSUE THREAD

**Issue by fcogutierrez** [AlejandroRuiz/PayPal.Forms#8]
Hi.

As you know, from the Paypal popup you can select the delivery address.

In order to manage this address internally in the system, would it be possible to receive this information in the `PaymentResult`? Is there any way to get this info?

It would be very useful in order to have a fully integration with the system.

**Comment by AlejandroRuiz** [comment]
At this moment this is not supported by Mobile SDK from paypal docs you have two solutions for this

1. Perform this query from your serverside code. Check this https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/

2. Use the custom shipping addres on the Buy() method and store it locally

**Comment by fcogutierrez** [comment]
Hi Alejandro.

I have tried to use the custom shipping address but I get this error in iOS: https://github.com/AlejandroRuiz/PayPal.Forms/issues/7

Thanks for your reply.

**Comment by AlejandroRuiz** [comment]
Did you tried using a non-zero price?

**Comment by fcogutierrez** [comment]
Yes @AlejandroRuiz any price is zero.

**Comment by fcogutierrez** [comment]
BTW, can I disable the address selection from the PayPal developer panel? And only to allow to the user to select the bank account/scan credit card.

**Comment by fcogutierrez** [comment]
@AlejandroRuiz do you think calling to `https://api.paypal.com/v1/payments/payment/{payment_id}` method I would get the delivery address?

I need to know the delivery address that the user select from the PayPal SDK in order to process the purchase in the Database.

Another option is to disable the address selection form the PayPal SDK, I don't know if this is possible or not.

Thanks.

**Comment by AlejandroRuiz** [comment]
@fcogutierrez  this is not an issue on PayPal Andriod/iOS SDK you must be validate the purchase on your server side please read here the official docs about this topic https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/ in that step you can retrieve the users shipping address
