### ISSUE TITLE
"The merchant does not accept payments of this type"

### ISSUE THREAD

**Issue by stavroaudi** [AlejandroRuiz/PayPal.Forms#82]
This question has been asked but not yet answered. 

I have the following setup: 

```
PayPal.Forms.CrossPayPalManager.Init(
new PayPalConfiguration(PayPalEnvironment.Production, "My_Live_Client_ID")
{
AcceptCreditCards = true,
MerchantName = "MyApp",
MerchantPrivacyPolicyUri = "https://www.privacypolicy.html",
MerchantUserAgreementUri = "https://www.terms.html"
},
this
);
```

When I try to make a payment, I get the error "The merchant does not accept payments of this type"

After research, I've seen that the problem could have been due to the fact that I don't have Paypal Pro, but seeing as that doesn't exist anymore, and seeing as my live environment seems to be setup correctly, I'm not sure what the problem could be? 

N.B. I haven't added my Live Client Secret in my app, and I'm not sure if it's necessary and where to put it.

@AlejandroRuiz any ideas?

**Comment by AlejandroRuiz** [comment]
Mobile Paypal SDK is now deprecated, so now some features are now disable if is your case I highly recommend to create your own Braintree implementation

**Comment by stavroaudi** [comment]
I am completely new to this, so I won't be able to create my own implementation of Braintree without detailed tutorial like you had for Paypal.Forms, and I can't find anything for Xamarin Forms. I know Braintree.Android and Braintree.iOS exist, but I don't know how to implement them in Xamarin.Forms

Any ideas on what I could do, where I might be able to get help?

Thanks!

**Comment by stavroaudi** [comment]
https://github.com/AlejandroRuiz/Braintree.Forms

Does this not work? It seems like you started it but don't work on it anymore

**Comment by AlejandroRuiz** [comment]
@stavroaudi I just started the project but I didn't get a chance of finish it and I dont have any ETA to completed that why I recommend to change to another option if this is super urgent for you

**Comment by stavroaudi** [comment]
Thanks for the quick reply, 

Although Paypal.Forms solution is deprecated, will it not work for simple card payments for now? I can see that a few have had the same issues but haven't specified how they've managed to overcome the error I get. My issue might be that I don't add the Client Secret, but I don't know where I'm supposed to add it. 

I've tried to get started with Braintree but I cannot figure out how to implement it without a solid tutorial for Xamarin Forms :(

**Comment by AlejandroRuiz** [comment]
direct credit card payments are now removed for new applicants so you have either use Braintree for paypal or any other alternative like Stripe

**Comment by stavroaudi** [comment]
Sadly neither have proper solutions for Xamarin Forms. Are you currently working on Braintree.Forms? It would be the best solution, and most likely the most popular one because I cannot find another solution at all at the moment. 

If so, do you have a estimated date of release? 

Thanks again

**Comment by stavroaudi** [comment]
Hi again @AlejandroRuiz 

Sorry for bothering, 

I just contacted paypal, and they said that I should be able to accept direct card payments, and that there might be something wrong with my implementation. They suggested I put in the client secret in my app, but I don't see where I should add it? I guess in AppDelegate and MainActivity but I don't see where exactly.

**Comment by AlejandroRuiz** [comment]
As I mentioned previously mobile paypal SDK is DEPRECATED if you want to use this feature you need to create your own Braintree or Express Checkout implementation
