### ISSUE TITLE
Improvements IOs SDK 13 ModalPresentationStyle

### ISSUE THREAD

**Issue by WermesRodrigues** [AlejandroRuiz/PayPal.Forms#86]
Hi Alejandro,

I hope you're very well, there is an improvement on IOS SDK 13 to show full screen the PayPalPaymentViewController.

Can you update this improvement below?

File PayPalManager

Method BuyItems and BuyItem.

            if (payment.Processable)
            {
                var paymentViewController = new PayPalPaymentViewController(payment, _nativeConfig, this);

                if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
                    paymentViewController.ModalPresentationStyle = UIModalPresentationStyle.FullScreen;

                var top = GetTopViewController(UIApplication.SharedApplication.KeyWindow);
                top.PresentViewController(paymentViewController, true, null);
            }

many thanks.

**Comment by AlejandroRuiz** [comment]
@WermesRodrigues thank you for the report it now the version 2.18.6 contains a fix for it
