### ISSUE TITLE
Layout problems on iOS - Apple rejection by this

### ISSUE THREAD

**Issue by albertoiglesias2001** [AlejandroRuiz/PayPal.Forms#87]
Apple reject my app today because this page is not "beautiful enough", check the label behid the PayPal logo.

Any way to solve this?

![Screen Shot 10-12-19 at 11 14 PM](https://user-images.githubusercontent.com/18347714/66708313-87011700-ed46-11e9-881a-f856f0329cde.PNG)

**Comment by AlejandroRuiz** [comment]
unfortunately the PayPal Mobile SDK is deprecated so this version only support old clients I just released a new version that fixes some issues with iOS 13 please check if the new update fix that issue ver: 2.18.6

**Comment by albertoiglesias2001** [comment]
this is terrible!  so , paypal mobile sdk will not work on new devices/ios?    I already tested with new version of this library but still with problem (I already opened a new issue)  but ok..   this problem is inside the libraries  not from you, right?  in this case I dont have choice?  thank you

**Comment by AlejandroRuiz** [comment]
right now Paypal Mobile SDK is deprecated so this librery only support old clients Paypal encourage to use Braintree for new apps
