### ISSUE TITLE
[Android] Buy function doesn't return any value

### ISSUE THREAD

**Issue by fravezzimattia** [AlejandroRuiz/PayPal.Forms#9]
MOBILE : Nexus 5
OS: Marshmallow (6.0)
Xamarin.Forms : 2.3.0.49

   When I try to pay (IN DEBUG) with last library PayPal.Froms (v2.0.6) the "CrossPayPalManager.Current.Buy" Method doesn't return any value.... When I debugging the apps doesn't stop to any breakpoint not even in to exception.

This is the code:

     try{
        var result = await CrossPayPalManager.Current.Buy(new PayPalItem("Carrello Numero " + CarrelloCheckout.id, TotaleCarrello, "EUR"), OrdineCheckout.total_shipping);

           if (result.Status == PayPalStatus.Cancelled)
            {
             }
            else if (result.Status == PayPalStatus.Error)
            {
             }
             else if (result.Status == PayPalStatus.Successful)
             {
              }
      }
      catch (Exception e)
      {
             var errore = e.Message;
      }

This is the output:

> 07-05 11:00:51.919 D/Mono    (13334): Assembly Ref addref FoxTour.PCL[0xab44d560] -> PayPal.Forms[0xab44d740]: 3
> 07-05 11:00:54.586 D/Mono    (13334): Assembly Ref addref PayPal.Forms[0xab44d740] -> Xamarin.Forms.Platform.Android[0xab44dce0]: 4
> 07-05 11:00:54.587 D/Mono    (13334): Assembly Ref addref PayPal.Forms[0xab44d740] -> Xamarin.PayPal.Android[0xab44e040]: 2
> 07-05 11:00:54.587 D/Mono    (13334): Assembly Ref addref PayPal.Forms[0xab44d740] -> Xamarin.PayPal.Android.CardIO[0xab44dfe0]: 2
> 07-05 11:00:54.649 W/paypal.sdk(13334): PayPalService created. API:23 PayPalSDK/PayPal-Android-SDK 2.14.1 (Android 6.0.1; LGE Nexus 5; )
> 07-05 11:00:54.773 I/System  (13334): Loaded time zone names for "en" in 35ms (33ms in ICU)
> 07-05 11:00:55.407 D/Mono    (13334): Assembly Ref addref Xamarin.Forms.Platform.Android[0xab44dce0] -> System.Xml[0x9ce03380]: 10
> 07-05 11:00:55.524 D/Mono    (13334): [0x950ff930] hill climbing, change max number of threads 12
> 07-05 11:00:55.634 W/paypal.sdk(13334): fr SN:3 PayPal Debug-ID: 970e8a6347ab0 [sandbox, 2.14.1;release]
> 07-05 11:00:55.991 I/WebViewFactory(13334): Loading com.google.android.webview version 51.0.2704.81 (code 270408100)
> 07-05 11:00:56.024 I/cr_LibraryLoader(13334): Time to load native libraries: 1 ms (timestamps 9130-9131)
> [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
> 07-05 11:00:56.024 I/cr_LibraryLoader(13334): Expected native library version number "51.0.2704.81", actual native library version number "51.0.2704.81"
> 07-05 11:00:56.035 V/WebViewChromiumFactoryProvider(13334): Binding Chromium to main looper Looper (main, tid 1) {f6e3f4c}
> 07-05 11:00:56.035 I/cr_LibraryLoader(13334): Expected native library version number "51.0.2704.81", actual native library version number "51.0.2704.81"
> 07-05 11:00:56.035 I/chromium(13334): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
> 07-05 11:00:56.051 I/cr_BrowserStartup(13334): Initializing chromium process, singleProcess=true
**> 07-05 11:00:56.059 E/ApkAssets(13334): Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
> 07-05 11:00:56.059 E/ApkAssets(13334): Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin**
> 07-05 11:00:56.137 W/cr_media(13334): Requires BLUETOOTH permission
> 07-05 11:00:56.189 I/card.io (13334): Checking hardware support...
> 07-05 11:00:56.189 I/card.io (13334): card.io 5.3.0 01/11/2016 16:07:03 -0600
> 07-05 11:00:56.198 D/card.io (13334): Loaded card.io decider library.
> 07-05 11:00:56.209 D/card.io (13334):     nUseNeon(): true
> 07-05 11:00:56.210 D/card.io (13334):     nUseTegra():false
> 07-05 11:00:56.210 D/card.io (13334):     nUseX86():  false
> 07-05 11:00:56.221 D/card.io (13334): Loaded opencv core library
> 07-05 11:00:56.249 D/card.io (13334): Loaded opencv imgproc library
> 07-05 11:00:56.258 I/card.io (13334): Loaded card.io NEON library
> Thread finished: <Thread Pool> #15
> 07-05 11:01:03.470 D/Mono    (13334): [0x950ff930] worker finishing
> The thread 'Unknown' (0xf) has exited with code 0 (0x0).
> 07-05 11:01:08.011 W/paypal.sdk(13334): fm SN:9 PayPal Debug-ID: 1306fed58bd3f [sandbox, 2.14.1;release]
> Thread finished: <Thread Pool> #14
> The thread 'Unknown' (0xe) has exited with code 0 (0x0).
> 07-05 11:01:18.571 W/paypal.sdk(13334): fg SN:11 PayPal Debug-ID: a0760a116279e [sandbox, 2.14.1;release]
> 07-05 11:01:22.769 D/Mono    (13334): [0x9c4be930] worker finishing
> Thread finished: <Thread Pool> #4

**Comment by AlejandroRuiz** [comment]
@fravezzimattia  it is working on my side please upload a project to your Github and track it here to see if i can replicate it

**Comment by AlejandroRuiz** [comment]
@fravezzimattia please update to ver. 2.14.4 https://www.nuget.org/packages/PayPal.Forms/

**Comment by fravezzimattia** [comment]
```
  public RelayCommand TapPayPalCommand
        {
            get
            {
                if (_tapPayPalCommand == null)
                {
                    _tapPayPalCommand = new RelayCommand(async () =>
                    {
                        try
                        {
                            var result = await CrossPayPalManager.Current.Buy(new PayPalItem("Carrello Numero " + CarrelloCheckout.id, TotaleCarrello, "EUR"), OrdineCheckout.total_shipping);

                            if (result.Status == PayPalStatus.Cancelled)
                            {
                                .....
                            }
                            else if (result.Status == PayPalStatus.Error)
                            {
                              ....
                            }
                            else if (result.Status == PayPalStatus.Successful)
                            {
                             ...
                            }
                        }
                        catch (Exception e)
                        {
                            var error = e.Message;
                        }
                    }, () => true);
                }
                return _tapPayPalCommand;
            }
        }
```

Doesn't work! after call to  CrossPayPalManager.Current.Buy, the application lost the thread and never return result...
